#!/usr/bin/env node

const path = require("path");
const { canonicalize, sha256, verifySignedReceipt } = require("../receipt-core");
const { verifyChain } = require("../verify-chain");
const { artifactHash, verifyArtifact } = require("../occurrence-return/crypto");
const { readJson, readJsonLines } = require("../occurrence-return/io");
const { CEILING, FIXTURE_ID } = require("./produce");

function verifyFederatedCrossing(root, expectedReturnHead, expectedMusHead) {
  const errors = []; const fail = (x) => errors.push(x);
  const read = (name) => { try { const x = readJson(path.join(root, name)); if (!x || typeof x !== "object" || Array.isArray(x)) throw new Error("NOT_OBJECT"); return x; } catch (e) { fail(`MISSING_OR_INVALID:${name}`); return null; } };
  if (!/^[0-9a-f]{64}$/.test(expectedReturnHead || "")) fail("EXPECTED_RETURN_HEAD_REQUIRED");
  if (!/^[0-9a-f]{64}$/.test(expectedMusHead || "")) fail("EXPECTED_MUS_HEAD_REQUIRED");
  const rolesFile = read("trust/role-bindings.json"); const roles = rolesFile?.roles || {};
  const names = ["campusA", "campusB", "world", "observer", "evidence", "compliance", "mus", "settlement"];
  for (const name of names) if (!roles[name]?.role || !roles[name]?.key_id || !roles[name]?.public_key) fail(`ROLE_BINDING_REJECTED:${name}`);
  const campusA = read("campuses/campus-a.json"), campusB = read("campuses/campus-b.json"), world = read("shared-world.json"), entryDoor = read("doors/door-a-to-k.json"), exitDoor = read("doors/door-k-to-b.json"), crossing = read("crossing.json"), trace = read("crossing-trace.json"), observation = read("observation.json"), evidence = read("crossing-evidence.json"), compliance = read("compliance-assessment.json"), receipt = read("mus-receipt.json"), settlement = read("settlement.json"), returnA = read("returns/return-a.json"), returnB = read("returns/return-b.json"), ackA = read("acknowledgements/ack-a.json"), ackB = read("acknowledgements/ack-b.json");
  for (const [name, value, role] of [["campusA",campusA,"campusA"],["campusB",campusB,"campusB"],["world",world,"world"],["entryDoor",entryDoor,"campusA"],["exitDoor",exitDoor,"campusB"],["crossing",crossing,"world"],["trace",trace,"observer"],["observation",observation,"observer"],["evidence",evidence,"evidence"],["compliance",compliance,"compliance"],["settlement",settlement,"settlement"],["returnA",returnA,"mus"],["returnB",returnB,"mus"],["ackA",ackA,"campusA"],["ackB",ackB,"campusB"]]) if (!value || !verifyArtifact(value, roles[role]).valid) fail(`ATTESTATION_REJECTED:${name}`);
  if (!campusA || !campusB || campusA.campus_id === campusB.campus_id || campusA.jurisdiction_envelope === campusB.jurisdiction_envelope) fail("DISTINCT_JURISDICTIONS_REQUIRED");
  if (!world || world.type !== "SharedWorld" || !Array.isArray(world.participant_refs) || canonicalize(world.participant_refs) !== canonicalize([campusA?.campus_id, campusB?.campus_id]) || canonicalize(world.participant_hashes) !== canonicalize([artifactHash(campusA), artifactHash(campusB)])) fail("SHARED_WORLD_BINDING_REJECTED");
  for (const [door, campus, from, to, id] of [[entryDoor,campusA,campusA?.campus_id,world?.shared_world_id,"door:fixture-a-to-k"],[exitDoor,campusB,world?.shared_world_id,campusB?.campus_id,"door:fixture-k-to-b"]]) if (!door || door.type !== "Door" || door.door_id !== id || door.from_ref !== from || door.to_ref !== to || door.authority_jurisdiction_ref !== campus?.jurisdiction_envelope || door.effect_capability !== "INERT_SCHEMA_AND_FIXTURE_ADMISSION_ONLY" || door.claim_ceiling !== "DOOR_DEFINES_POSSIBILITY_NOT_OCCURRENCE") fail("DOOR_BINDING_OR_CEILING_REJECTED");
  if (!crossing || crossing.type !== "Crossing" || crossing.source_campus_ref !== campusA?.campus_id || crossing.target_campus_ref !== campusB?.campus_id || crossing.shared_world_hash !== artifactHash(world) || crossing.entry_door_hash !== artifactHash(entryDoor) || crossing.exit_door_hash !== artifactHash(exitDoor) || crossing.external_effect !== "NOT_CLAIMED" || crossing.succession_effect !== "NONE" || crossing.future_authority_effect !== "NONE") fail("CROSSING_BINDING_OR_CEILING_REJECTED");
  if (!trace || trace.crossing_hash !== artifactHash(crossing) || trace.lawfulness_status !== "NOT_PROVEN_BY_TRACE" || trace.claim_ceiling !== "TRACE_IS_NOT_PROOF_OF_LAWFULNESS") fail("TRACE_NOT_PROOF_REJECTED");
  if (!observation || observation.crossing_hash !== artifactHash(crossing) || observation.trace_hash !== artifactHash(trace) || observation.external_effect !== "NOT_OBSERVED_OR_CLAIMED") fail("OBSERVATION_BINDING_REJECTED");
  if (!evidence || evidence.crossing_hash !== artifactHash(crossing) || evidence.observation_hash !== artifactHash(observation) || evidence.lawful_compliance_evidence !== "NOT_ESTABLISHED") fail("EVIDENCE_BINDING_OR_LAWFULNESS_REJECTED");
  if (!compliance || compliance.crossing_hash !== artifactHash(crossing) || compliance.evidence_hash !== artifactHash(evidence) || compliance.determination !== "NOT_ASSESSED_FOR_CONSTITUTIONAL_LAWFULNESS" || compliance.succession_effect !== "NONE") fail("COMPLIANCE_STANDING_REJECTED");
  if (!receipt || !verifySignedReceipt(receipt, roles.mus?.public_key).valid || receipt.receipt_hash !== expectedMusHead) fail("MUS_RECEIPT_OR_HEAD_REJECTED");
  const chain = verifyChain({ ledgerPath: path.join(root, "ledger/ledger.jsonl"), trustedKeysPath: path.join(root, "trust/receipt-keys.json"), expectedHeadHash: expectedMusHead, expectedRecordCount: 1 }); if (!chain.valid) fail("MUS_CHAIN_REJECTED");
  if (!settlement || settlement.crossing_hash !== artifactHash(crossing) || settlement.evidence_hash !== artifactHash(evidence) || settlement.mus_receipt_hash !== receipt?.receipt_hash || settlement.succession_effect !== "NONE" || settlement.future_authority_effect !== "NONE") fail("SETTLEMENT_BINDING_REJECTED");
  for (const [envelope, ack, campus, side] of [[returnA,ackA,campusA,"a"],[returnB,ackB,campusB,"b"]]) { if (!envelope || envelope.recipient_campus_ref !== campus?.campus_id || envelope.crossing_hash !== artifactHash(crossing) || envelope.settlement_hash !== artifactHash(settlement) || envelope.automatic_incorporation !== false || envelope.shared_succession !== false || envelope.future_authority_effect !== "NONE" || !ack || ack.return_ref !== envelope.return_id || ack.return_hash !== artifactHash(envelope) || ack.recipient_campus_ref !== campus?.campus_id || ack.incorporated !== false || ack.shared_succession !== false) fail(`RECIPIENT_SPECIFIC_RETURN_REJECTED:${side}`); }
  let journal=[]; try { journal=readJsonLines(path.join(root,"return-journal.jsonl")); } catch { fail("RETURN_JOURNAL_INVALID"); } if (journal.length !== 5 || artifactHash(journal.at(-1)) !== expectedReturnHead || !journal[0] || journal[0].settlement_id !== settlement?.settlement_id || journal[1]?.return_id !== returnA?.return_id || journal[2]?.acknowledgement_id !== ackA?.acknowledgement_id || journal[3]?.return_id !== returnB?.return_id || journal[4]?.acknowledgement_id !== ackB?.acknowledgement_id) fail("RETURN_JOURNAL_RECONSTRUCTION_REJECTED");
  return { ok: errors.length===0, terminal_state: errors.length ? "NOT_CLOSED" : "FEDERATED_RETURNED_UNPROMOTED", claim_ceiling: CEILING, errors, excluded_claims:["production-federation","constitutional-lawfulness","shared-succession","human-authority","external-effect"] };
}
if(require.main===module){ const [root,r,m]=process.argv.slice(2); const out=verifyFederatedCrossing(root,r,m); console.log(JSON.stringify(out)); process.exitCode=out.ok?0:1; }
module.exports={verifyFederatedCrossing};
